title:
  en: Page
  de: Seite

icon: 📝

options:
  preview: "{{ page.frontendUrl }}"

columns:
  - width: 2/3
    sections:
      blocks: sections/blocks

  - width: 1/3
    sections:
      cover: sections/cover
      description: sections/description
      pages: sections/pages
      images: sections/images
